### ISSUE TITLE
getAccessToken API method

### ISSUE THREAD

**Issue by balapalanisamy** [janrain-rest/janrain-rest#13]
The method for getAccessToken is POST and currently it is GET.

https://janrain-education-center.knowledgeowl.com/home/accessgetaccesstoken

**Comment by chalomciandt** [comment]
Hi! Thanks for the report. I have tested recently and Janrain seem to accept both GET and POST requests in this endpoint. Are you encountering any error?

**Comment by chalomciandt** [comment]
Ok, after some fiddling, I've found out that the `Authentication::getAccessToken` method is always sending a `for_client` parameter to Janrain, which may not be intended. I'll look into making this parameter optional, this may fix permission errors.

**Comment by chalomciandt** [comment]
Should be fixed in #14 please let us know if it worked
