### ISSUE TITLE
/access/useVerificationCode should be POST method

### ISSUE THREAD

**Issue by balapalanisamy** [janrain-rest/janrain-rest#2]
The API /access/useVerificationCode in Authentication.php should use POST method. 

https://educationcenter.janrain.com/home/accessgetverificationcode

**Comment by janrain-rest** [comment]
This issue was merged on [https://github.com/janrain-rest/janrain-rest/pull/3](https://github.com/janrain-rest/janrain-rest/pull/3)

Thank you @ymd_cit
