### ISSUE TITLE
Add entity.create endpoint

### ISSUE THREAD

**Issue by marcoslor** [janrain-rest/janrain-rest#21]
Hi!

I'm opening this issue to track and discuss the pull request https://github.com/janrain-rest/janrain-rest/pull/20.

As I've commented there, our project (which uses the janrain_connect module) need to call Janrain's [/entity.create](https://techdocs.akamai.com/identity-cloud-entity/reference/post-entity-create) endpoint.

Before adding a new method in janrain_connect, this library should have an interface for this endpoint.

**Comment by janrain-rest** [comment]
Thanks a lot @marcoslor 

Merged and updated the packagist: https://packagist.org/packages/janrainrest/janrainrest so you can use composer

I also updated Janrain connect on Drupal

Thanks for your contribution
